name: test

on: [push, pull_request]

jobs:
  build:
    # Skip building pull requests from the same repository
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    env:
      BUILD_TYPE: Release
    steps:

    - name: do
      run: |
          Invoke-WebRequest -Uri "https://github.com/gmh5225/android-ndk-windows-llvm-msvc/releases/download/r26c/android-ndk-r26c-windows-llvm-msvc.7z" -OutFile "android-ndk-r26c-windows-llvm-msvc.7z"
          7z x "android-ndk-r26c-windows-llvm-msvc.7z"
          del android-ndk-r26c-windows-llvm-msvc.7z
          7z a android-ndk-r26c-windows-llvm-msvc.zip android-ndk-r26c-windows-llvm-msvc

    - name: Upload ndk-26c
      uses: actions/upload-artifact@v2
      with:
        name: android-ndk-r26c-windows-llvm-msvc
        path: android-ndk-r26c-windows-llvm-msvc.zip
        
