name: test

on: [push, pull_request]

jobs:
  build:
    # Skip building pull requests from the same repository
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    env:
      BUILD_TYPE: Release
    steps:

    - name: Setup build deps
      run: |
          sudo wget -qO /usr/local/bin/ninja.gz https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip \
          && sudo gunzip /usr/local/bin/ninja.gz \
          && sudo chmod a+x /usr/local/bin/ninja \
          && sudo apt-get install build-essential make cmake \
          && sudo apt-get install p7zip-full p7zip-rar \
          && sudo apt install g++-11-aarch64-linux-gnu libstdc++-11-dev-arm64-cross gcc-11 g++-11 \
          && wget -nv https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz && tar xf clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz

          clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04/bin/clang --version
          
        
